### PR TITLE
Added the property [callback] to @jsFunction object

### PR DESCRIPTION
**Pull request by alexandreu**

### CODE REVIEW

**Comment by alexandreu** [comment]
//callback would be another @jsFunction object that would be called upon success. For instance:

<pre>
myElement {
   behavior: @click {
      action: @jsFunction {
         name: doStuff;
         arguments: "hello", "world";
         callback: doEvenMoreStuff;
      }
   }
}
</pre>

//this callback would recieve the response of doStuff as its parameters. I think is the proper way to implement asynchronous calls.

**Comment by veosotano** [comment]
Then, how does the function signal that it succeeded? By returning true or false? Shouldn't a callback be passed in as an argument? Or inside an object as an argument, such as: 

```
myElement { behavior: @click { @js { "
   myFunction ( {
      success: function() { alert("oh yeah"); },
      error: function() { alert("oh noes!"; }
   });
"} } }
```

**Comment by veosotano** [comment]
Anyone has any more input on this?

**Comment by alexandreu** [comment]
I was thinking something like this:

<pre>
myElement { behavior: @click { @js { "
   myFunction ( {
      //whatever implementation
   callback: function (data) {     //this function recieves the response whatever this is }
  });
"} } }
</pre>

**Pull request closed without merging**
