### PR TITLE
Linux port

### PR DESCRIPTION
**Pull request by Ragnis**
This is mostly based on vp_'s Windows port.

### CODE REVIEW

**Comment by matzipan** [comment]
Way to go!!!

On 8 March 2012 19:07, Ragnis Armus <
reply@reply.github.com

**Comment by matzipan** [comment]
What are the dependencies? I guess it works in ubuntu, but what is actually
needed to run it? Just x11?

**Comment by Ragnis** [comment]
I think so.
Also it has to be run from terminal, as there is no graphical "Open file" dialog.

The compiled binary is available at http://www.upload.ee/files/2144266/axr.html

**Comment by Ragnis** [comment]
Has anyone tried if the binary works?

**Comment by matzipan** [comment]
I downloaded that file to my laptop. Chmod +x and ./axr did not work for me
at all.

Yours,
   Andrei

On 10 March 2012 13:31, Ragnis Armus <
reply@reply.github.com

**Pull request merged**
